/*
 * This source file was generated by the Gradle 'init' task
 */
package com.grocery;

import jakarta.servlet.Filter;

import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;
import org.springframework.web.filter.DelegatingFilterProxy;

import com.grocery.security.SpringSecurityConfig;
import com.grocery.business.SpringBusinessConfig;
import com.grocery.web.SpringWebConfig;

public class SpringAppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

	
    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class<?>[] { SpringWebConfig.class };
    }

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class<?>[] { SpringBusinessConfig.class, SpringSecurityConfig.class };
        
    }

	@Override
	protected String[] getServletMappings() {
		return new String[] { "/" };
	}

    @Override
	public Filter[] getServletFilters() {
		DelegatingFilterProxy delegatingFilterProxy = new DelegatingFilterProxy();
		delegatingFilterProxy.setTargetBeanName("springSecurityFilterChain");
		return new Filter[] { delegatingFilterProxy };
	}
}