/*
 * This source file was generated by the Gradle 'init' task
 */
package com.grocery;

import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;

import com.grocery.business.SpringBusinessConfig;
import com.grocery.web.SpringWebConfig;

public class SpringAppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

	
    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class<?>[] { SpringWebConfig.class, SpringBusinessConfig.class };
    }

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return null;
    }

	@Override
	protected String[] getServletMappings() {
		return new String[] { "/" };
	}
}